#!/bin/bash
#lazygit - add commit and push to current branch in one easy command

branch=$(git branch | grep \*)
branch=${branch//\*\ /}

printf "\nCommitting to $branch.\n\nEnter commit message: \n"
read message

git add --all
git commit -am "$message"
git push origin $branch


